<?php


namespace backend\components;


use backend\models\Category;
use yii\base\Widget;
use yii\helpers\Html;

class widgetCategory extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

    }
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
    public function getChild($id){
        $childs = Category::find()->where(['parent'=>$id])->all();
        if($childs){
            echo '<ul>';
            foreach($childs as $cate){
                echo '<li>'.$cate->name.'</li>>';
                $this->getChild($cate->id);
            }
            echo '</ul>';
        }
    }
}